# fly.toml app configuration file generated for datafeed-webserver on 2023-11-07T16:28:48-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datafeed-webserver"
primary_region = "lax"

[build]

[http_service]
  internal_port = 64013
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
